name: Publish Docker image

on:
  push:
    tags:
      - "v[0-9].*[0-9]"

env:
  DOCKER_IMAGE_TAG: ${{ github.ref_name }}

jobs:
  push_to_registry:
    name: Push Docker image to Dockerhub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: deepset/prompthub:latest,deepset/prompthub:${{ env.DOCKER_IMAGE_TAG }}

  deploy:
    needs: push_to_registry
    uses: ./.github/workflows/ecs-deploy.yml
    secrets: inherit
    with:
      docker-image: deepset/prompthub:${{ env.DOCKER_IMAGE_TAG }}
